task_name: long_term_forecast
is_training: 1
root_path: ./dataset/PEMS/
data_path: PEMS04.npz
model_id: PEMS04
model: DMNet
data: PEMS
features: M
seq_len: 12
label_len: 0
pred_len: 12
e_layers: 5
d_layers: 1
factor: 3
enc_in: 307
dec_in: 307
c_out: 307
des: Exp
itr: 1
use_norm: 0
channel_independence: 0
d_model: 128
d_ff: 256
batch_size: 32
learning_rate: 0.001
train_epochs: 100
patience: 10
down_sampling_layers: 2
down_sampling_method: avg
down_sampling_window: 2
